version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=socialieus
      - POSTGRES_USER=ossarioglu
      - POSTGRES_PASSWORD=ossarioglu
  webapp:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/webapp
    ports:
      - "8000:8000"
    depends_on:
      - db