# Generated by Django 3.2.9 on 2021-12-05 14:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_auto_20211205_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='deadlineForUpdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 14, 40, 44, 246225, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offering',
            name='providerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offering',
            name='serviceInfo',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='offering',
            name='startingDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 14, 40, 44, 246190, tzinfo=utc)),
        ),
    ]
