# Generated by Django 3.2.9 on 2021-12-08 18:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211205_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagName', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='offering',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterField(
            model_name='offering',
            name='deadlineForUpdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 18, 1, 16, 259711, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offering',
            name='startingDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 18, 1, 16, 259674, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='offering',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tag'),
        ),
    ]
