# Generated by Django 3.2.9 on 2021-12-14 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20211208_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='deadlineForUpdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 17, 8, 58, 894428, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offering',
            name='startingDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 17, 8, 58, 894388, tzinfo=utc)),
        ),
    ]
