# Generated by Django 3.2.9 on 2021-12-14 17:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20211214_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='deadlineForUpdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 17, 9, 20, 940153, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offering',
            name='startingDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 17, 9, 20, 940116, tzinfo=utc)),
        ),
    ]
