# Generated by Django 3.2.9 on 2021-12-18 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20211214_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='recurrance',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='offering',
            name='deadlineForUpdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='offering',
            name='startingDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagName',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
