# Generated by Django 3.2.9 on 2021-12-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20211218_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='picture',
            field=models.ImageField(default=1, upload_to=None),
            preserve_default=False,
        ),
    ]
