# Generated by Django 3.2.9 on 2021-12-18 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_offering_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(max_length=10)),
                ('userReputation', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('creditAmount', models.PositiveIntegerField(default=10)),
                ('userDetails', models.TextField(blank=True, max_length=200, null=True)),
                ('userLocation', models.CharField(max_length=50)),
                ('userPicture', models.ImageField(upload_to=None)),
                ('creditInprocess', models.IntegerField(default=0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
