# Generated by Django 3.2.9 on 2021-12-28 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('serviceID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='New', max_length=10)),
                ('keywords', models.CharField(max_length=100)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('serviceInfo', models.TextField(blank=True, max_length=200, null=True)),
                ('startingDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.PositiveIntegerField(default=1)),
                ('meetingType', models.CharField(default='FaceToFace', max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('recurrance', models.PositiveIntegerField(default=1)),
                ('deadlineForUpdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('providerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagName', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Requestservice',
            fields=[
                ('requestID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serviceType', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('requesterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('serviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.offering')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(max_length=10)),
                ('userReputation', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('creditAmount', models.PositiveIntegerField(default=10)),
                ('userDetails', models.TextField(max_length=200, null=True)),
                ('userLocation', models.CharField(max_length=50)),
                ('userPicture', models.ImageField(default='male.png', null=True, upload_to='')),
                ('creditInprocess', models.IntegerField(default=0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='offering',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.tag'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('noteID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('noteContent', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('receiverID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('serviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.offering')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedbackID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('rating', models.PositiveIntegerField(default=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('giverID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbackGiverID', to=settings.AUTH_USER_MODEL)),
                ('serviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.offering')),
                ('takerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbackReceiverID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
