# Generated by Django 3.2.10 on 2021-12-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='picture',
            field=models.ImageField(blank=True, upload_to='offer_images'),
        ),
    ]
