# Generated by Django 3.2.9 on 2021-12-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='picture',
            field=models.ImageField(default='Cat03.png', null=True, upload_to=''),
        ),
    ]
