# Generated by Django 3.2.9 on 2021-12-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userDetails',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
