# Generated by Django 3.2.9 on 2022-01-01 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing', '0002_alter_offering_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serviceType', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('approverID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approverForAssignementID', to=settings.AUTH_USER_MODEL)),
                ('requestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.requestservice')),
                ('requesterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesterForAssignementID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
