# Generated by Django 3.2.9 on 2021-12-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_profile_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userPicture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
