# Generated by Django 3.2.9 on 2022-01-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
