# Generated by Django 3.2.10 on 2021-12-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20211227_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='picture',
            field=models.ImageField(default='Cat03.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userPicture',
            field=models.ImageField(default='male.png', null=True, upload_to=''),
        ),
    ]
