# Generated by Django 3.2.9 on 2022-01-02 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_alter_notification_receiverid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='serviceID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbackForService', to='landing.offering'),
        ),
    ]
