# Generated by Django 3.2.9 on 2022-01-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_alter_feedback_serviceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='status',
            field=models.CharField(default='Open', max_length=100),
        ),
    ]
