# Generated by Django 3.2.9 on 2022-01-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_alter_offering_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='picture',
            field=models.ImageField(default='Cat03.png', null=True, upload_to='Services'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='status',
            field=models.CharField(default='New', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userPicture',
            field=models.ImageField(default='male.png', null=True, upload_to='Profiles'),
        ),
    ]
