# Generated by Django 3.2.9 on 2022-01-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_alter_profile_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Confirmed by provider', 'Confirmed by provider'), ('Confirmed by receiver', 'Confirmed by receiver'), ('Closed', 'Closed')], default='Open', max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 5), (3, 5), (4, 5), (5, 5)], default=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('Unread', 'Unread'), ('Read', 'Read')], default='Unread', max_length=100),
        ),
        migrations.AlterField(
            model_name='offering',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Closed', 'Closed'), ('Assigned', 'Assigned')], default='New', max_length=100),
        ),
    ]
