# Generated by Django 3.2.9 on 2022-01-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_auto_20220104_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='recurrancePeriod',
            field=models.CharField(choices=[('None', 'None'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='offering',
            name='serviceType',
            field=models.CharField(choices=[('Offering', 'Offering'), ('Event', 'Event')], default='Offering', max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
