# Generated by Django 3.2.9 on 2022-01-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_alter_offering_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Closed', 'Closed'), ('Assigned', 'Assigned')], default='New', max_length=10),
        ),
    ]
