version: "3.9"
   
services:
    socializeus:
        image: ossarioglu/socializeus:i2
        build: .
        container_name: socializeus
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - pgdb
    pgdb:
        image: ossarioglu/socializeus:i1
        container_name: pgdb
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data/
volumes:
    pgdata:
 #       - POSTGRES_INITDB_ARGS='-E SQL_ASCII --auth-host=scram-sha-256'

